spring:
  application:
    name: webshopping
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://34.64.172.140:5000/project2
    username: master
    password: password
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      s3:
        bucket: elice5-3team
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    stream-write-constraints:
      max-nesting-depth: 2000

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb